[package]
name = "rule-engine"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Rule engine for Crazy Puzzle"

[dependencies]
indexmap = { version = "2.10", features = ["serde"] }
ron = "0.10"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
